version: "3"
services:
  app:
    build: . 
    depends_on:
      - mongo
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.type: LoadBalancergit 
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_HOST=mongodb
      - MONGO_DB=firstmongo 
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local